name: "Forgotten issue finder"
description: "Lists issues of a repo that have a merged PR created at a later date referencing them."
icon: "search"
color: "gray"
inputs:
  ignore-label:
    description: "Issue label which can be used to mark issues to ignore them"
    required: false
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
outputs:
  issue-links:
    description: "List of links that need to be checked"
runs:
  using: "node12"
  main: "dist/index.js"
